# Generated by Django 5.2.6 on 2025-10-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='criado',
            new_name='criado_at',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='modificado',
            new_name='modificado_at',
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='produto/', verbose_name='Imagem'),
        ),
    ]
